### ISSUE TITLE
Server Start "Default theme not set"

### ISSUE THREAD

**Issue by MatthewMcD** [akmittal/hugofy-vscode#10]
I am new to Hugo. When I run my project from the command line it build and runs fine. When I use hugofy I get: 

> Default theme not set. Please set one.

 Is there a configuration that hugofy is expecting that the server safely ignores?

**Comment by peteryates** [comment]
It would appear that running `Hugofy: Set Theme` first fixes this, despite me having a `theme: something` in my config file already.

**Comment by MatthewMcD** [comment]
Yes, that was the issue.
