### ISSUE TITLE
Error running server

### ISSUE THREAD

**Issue by cesarfong** [akmittal/hugofy-vscode#4]
When i use Start Server in VS Code in Mac OS 10.12.3 it throws me Error running server

**Comment by Thojad** [comment]
I have the same problem too.

**Comment by akmittal** [comment]
I do not have access to MacOS. Can someone tell what could be be problem.

**Comment by rpeshkov** [comment]
Hi @akmittal. I've added PR that fixes this issue

**Comment by akmittal** [comment]
Thanks @rpeshkov merged and published
